[package]
name = "commando"
version = "0.2.0"
authors = ["Hammed Anuoluwapo Pelumi <stationphast@gmail.com>"]
description = "An interactive CLI tool to help you write conventional commit messages with ease."
license = "MIT"
edition = "2021"
readme = "README.md"
homepage = "https://github.com/phastboy/commando"
repository = "https://github.com/phastboy/commando"
documentation = "https://github.com/phastboy/commando#readme"
keywords = ["cli", "conventional commits", "interactive"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
color-eyre = "0.6.3"

[release]
push-remote = "origin"
allow-branch = ["main"]

[badges]
github-actions = { repository = "phastboy/commando", workflow = "CI" }
maintenance = { status = "actively-developed" }
